### PR TITLE
Fix pipeline database variable missing a closing "}"

### PR DESCRIPTION
**Pull request by kierenevans**

### CODE REVIEW

**Comment by andytson** [comment]
:)

**Comment by andytson** [comment]
this {{name}} in itself is a annoying issue. When we had magento as a submodule, it would replace some magento js templating that used {{name}}

**Comment by kierenevans** [comment]
Could we rename it throughout the codebase as `{{hem_project_name}}` perhaps?

**Comment by andytson** [comment]
I'm wondering if {{Hem.project_config.name}}, in line with the actual ruby statement. I'd need to think about whether making {{Hem...}} dynamic though as an addition would be too much

**Pull request merged**
